# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }} 
          AWS_S3_BUCKET: model-repository
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: './src/bioengine-model-runner'      # optional: defaults to entire repository